#!/bin/sh -h 
dir_name=`dirname $0`
if [ "${dir_name}" = "." ]; then
    cd $dir_name
    dir_name=`pwd`
fi
if [ -d $dir_name/../../../../../.. ]; then
    cd $dir_name/../../../../../..
fi
if [ -f /ws/rakeshku-bgl/fpga/simv.daidir/debug_dump/fsearch/.create_fsearch_db ]; then
    if [ ! -f /ws/rakeshku-bgl/fpga/simv.daidir/debug_dump/fsearch/fsearch.db ]; then
        /ws/rakeshku-bgl/fpga/simv.daidir/debug_dump/fsearch/.create_fsearch_db
    fi
fi
