#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned RP;
typedef unsigned RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned long long TimeStamp64;
typedef U  TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef union {
    double I668;
    unsigned long long I669;
    unsigned  I670[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I677;
    E_fn  I678;
    struct iptmpl * I679;
    unsigned I681;
    struct eblk * I682;
} eblk_struct;
typedef struct {
    RP  I677;
    RP  I678;
    RP  I679;
    unsigned I681;
    RP  I682;
} RmaEblk;
typedef union {
    double I668;
    unsigned long long I669;
    unsigned  I670[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I708;
    RmaEblk  I676;
    U  I709;
    US  I710 :1;
    US  I711 :4;
    US  I176 :2;
    US  state :2;
    US  I713 :1;
    US  I714 :2;
    US  I715 :2;
    US  fHsim :1;
    US  I716 :1;
    scalar  newval;
    scalar  I718;
    RP  I719;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I698;
    scalar  I699;
    scalar  I700;
    scalar  I701;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I703;
    EBLK  I704;
    void * I705;
    UP   I706[1];
};
struct RmaMPSched {
    RP  I698;
    scalar  I699;
    scalar  I700;
    scalar  I701;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I703;
    RmaEblk  I704;
    RP  I705;
    RP   I706[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I698;
    scalar  I699;
    scalar  I700;
    scalar  I701;
    scalar  I176;
    U  I703;
    RmaEblk  I704;
    scalar  I715;
    scalar  I723;
    scalar  I724;
    scalar  I725;
    U  I726;
    RmaClockStruct  I727;
    RmaClockStruct  I728;
    U  state;
    U  I729;
    RP  I679;
    RP  I730;
    RP  I731;
    RP   I706[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I733;
    void * I734;
};
typedef struct {
    RmaEblk  I676;
    RP  I735;
    scalar  I736;
    scalar  I715;
    scalar  I737;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I698;
    scalar  I699;
    scalar  I700;
    scalar  I701;
    scalar  fHsim :1;
    scalar  I176 :6;
    U  I703;
    RmaEblk  I704;
    scalar  I715;
    scalar  I723;
    scalar  I724;
    scalar  I725;
    U  state :4;
    U  I739 :28;
    RmaClockStruct  I727;
    RmaClockStruct  I728;
    RP  I740;
    RP  I679;
    RP  I741;
    RP   I706[1];
};
typedef struct red_t {
    U  I742;
    U  I743;
    U  I634;
} RED;
typedef struct predd {
    PD_e  I176;
    RED   I744[0];
} PREDD;
union rhs_value {
    vec32  I745;
    scalar  I736;
    vec32  * I715;
    double I746;
    U  I747;
};
typedef struct nbs_t {
    struct nbs_t * I748;
    struct nbs_t * I750;
    void (* I751)(struct nbs_t * I752);
    unsigned I753 :1;
    unsigned I754 :1;
    unsigned I755 :1;
    unsigned I756 :1;
    unsigned I757 :27;
    void * I758;
    U  I759;
    union rhs_value I760;
    vec32  I668;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I762;
} NBS;
typedef struct {
    RP  I763;
    RP  I730;
    RP  I679;
    RP  I731;
    RmaEblk  I676;
    RmaEblk  I764;
    RP  I765;
    scalar  I736;
    scalar  I715;
    char state;
    uscope_t  I766;
    U  I767;
    RP  I768;
    scalar  I723;
    scalar  I724;
    scalar  I725;
    RmaClockStruct  I727;
    RmaClockStruct  I728;
    RP  I705;
} RmaPulse;
typedef struct {
    UP  I769;
    int * I770;
} TypeData;
struct etype {
    U  I552 :8;
    U  I553 :24;
    U  I554;
    U  I555 :1;
    U  I556 :1;
    U  I557 :1;
    U  I558 :1;
    U  I559 :1;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :1;
    U  I564 :4;
    U  I565 :1;
    U  I566 :1;
    U  I567 :1;
    U  I568 :1;
    U  I569 :1;
    U  I570 :1;
    U  I571 :1;
    U  I572 :1;
    U  I573 :2;
    U  I574 :1;
    U  I575 :2;
    U  I576 :1;
    U  I577 :1;
    U  I578 :4;
    TypeData  * I579;
    U  I580;
    U  I581;
    U  I582 :1;
    U  I583 :1;
    U  I584 :1;
    U  I585 :1;
    U  I586 :2;
    U  I587 :2;
    U  I588 :1;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :1;
    U  I593 :1;
    U  I594 :1;
    U  I595 :1;
    U  I596 :16;
};
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I774 :1;
    U  I775 :1;
    U  I776 :1;
    U  I777 :1;
    U  I778 :1;
    U  I779 :1;
    U  I780 :1;
    U  I781 :1;
    U  I782 :1;
    U  I783 :1;
    U  I784 :1;
    U  I785 :1;
    U  I786 :1;
    U  I787 :1;
    U  I788 :1;
    U  I789 :1;
    U  I790 :1;
    U  I791 :1;
    QIRDModuleType  I792 :2;
    U  I793 :1;
    U  I794 :1;
    U  I795 :1;
    U  I796 :1;
    U  I797 :1;
    U  I798 :1;
    U  I799 :1;
    U  I800 :1;
    U  I801 :1;
    U  I802 :1;
    U  I803 :1;
    U  I804 :1;
    U  I805 :1;
    U  I806 :1;
    U  I807 :1;
    U  I808 :1;
    U  I809 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    UP  * I20;
    U  I21;
    UP  * I22;
    U  I23;
    U  I24;
    U  I25;
    U  * I26;
    U  * I27;
    void * I28;
    void * I29;
    U  I30;
    int I31;
    UP  I32;
    U  I33;
    U  I34;
    U  I35;
    UP  I36;
    U  * I37;
    BitFlags  I38;
    U  I39;
    U  I40;
    U  I41;
    U  I42;
    U  I43;
    U  * I44;
    U  I45;
    U  * I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  I52;
    U  I53;
    U  * I54;
    U  * I55;
    U  I56;
    U  I57;
    U  * I58;
    U  I59;
    U  * I60;
    U  I61;
    U  I62;
    U  I63;
    U  I64;
    U  * I65;
    U  I66;
    U  * I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  I72;
    U  I73;
    U  * I74;
    char * I75;
    U  I76;
    U  I77;
    U  I78;
    U  I79;
    U  I80;
    U  * I81;
    U  I82;
    U  I83;
    UP  * I84;
    U  I85;
    U  I86;
    UP  * I87;
    U  I88;
    U  I89;
    U  I90;
    U  I91;
    U  I92;
    U  I93;
    U  * I94;
    U  I95;
    U  I96;
    U  * I97;
    U  * I98;
    U  * I99;
    U  * I100;
    U  * I101;
    U  I102;
    U  I103;
    struct taskInfo * I104;
    U  I106;
    U  I107;
    int * I108;
    UP  * I109;
    U  * I110;
    U  I111;
    U  I112;
    U  I113;
    U  I114;
    U  I115;
    struct qrefer * I116;
    U  * I118;
    unsigned * I119;
    void * I120;
    U  I121;
    U  I122;
    struct classStaticReferData * I123;
    U  I125;
    U  I126;
    U  I127;
    U  * I128;
    U  I129;
    U  * I130;
    U  I131;
    U  I132;
    U  I133;
    U  * I134;
    U  I135;
    U  * I136;
    U  I137;
    U  I138;
    U  * I139;
    U  I140;
    U  I141;
    U  * I142;
    U  * I143;
    U  * I144;
    U  I145;
    U  I146;
    U  I147;
    U  I148;
    U  I149;
    struct qrefee * I150;
    U  * I152;
    U  I153;
    struct qdefrefee * I154;
    U  * I156;
    int (* I157)(void);
    char * I158;
    U  I159;
    U  I160;
    void * I161;
    void * I162;
    NumLibs_t  I163;
    char * I164;
    U  * I165;
    U  I166;
    U  I167;
    U  I168;
    U  I169;
    U  I170;
    U  * I171;
    U  * I172;
    int I173;
    struct clock_load * I174;
    int I189;
    struct clock_data * I190;
    int I206;
    struct clock_hiconn * I207;
    U  I211;
    int I212;
    U  I213;
    int I214;
    U  * I215;
    U  * I216;
    U  I217;
    void * I218;
    U  I219;
    U  I220;
    UP  * I221;
    void * I222;
    U  I223;
    UP  * I224;
    U  * I225;
    int (* I226)(void);
    U  * I227;
    UP  * I228;
    U  * I229;
    U  I230 :1;
    U  I231 :31;
    U  I232;
    U  I233;
    UP  * I234;
    U  * I235;
    U  I236 :1;
    U  I237 :1;
    U  I238 :1;
    U  I239 :1;
    U  I240 :28;
    U  I241;
    U  I242;
    U  I243;
    U  I244 :31;
    U  I245 :1;
    UP  * I246;
    UP  * I247;
    U  * I248;
    U  * I249;
    U  * I250;
    UP  * I251;
    UP  * I252;
    UP  * I253;
    U  * I254;
    UP  * I255;
    UP  * I256;
    UP  * I257;
    char * I258;
    U  I259;
    U  I260;
    U  I261;
    UP  * I262;
    UP  * I263;
    UP  * I264;
    UP  * I265;
    UP  * I266;
    UP  * I267;
    UP  * I268;
    UP  * I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    U  I275;
    U  I276;
    U  I277;
    U  I278;
    U  I279;
    U  I280;
    U  I281;
    U  I282;
    char * I283;
    U  * I284;
    U  I285;
    U  I286;
    U  I287;
    UP  * I288;
    UP  * I289;
    UP  * I290;
    UP  * I291;
    struct daidirInfo * I292;
    struct vcs_tftable * I294;
    U  I296;
    UP  * I297;
    UP  * I298;
    U  I299;
    U  I300;
    U  I301;
    UP  * I302;
    U  * I303;
    struct qird_hil_data * I304;
    UP  (* I306)(void);
    UP  (* I307)(void);
    UP  (* I308)(void);
    UP  (* I309)(void);
    UP  (* I310)(void);
    int * I311;
    int (* I312)(void);
    char * I313;
    UP  * I314;
    UP  * I315;
    UP  (* I316)(void);
    int (* I317)(void);
    int * I318;
    int (* I319)(void);
    int * I320;
    char * I321;
    U  * I322;
    U  * I323;
    U  * I324;
    U  * I325;
    void * I326;
    U  I327;
    void * I328;
    U  I329;
    U  I330;
    U  I331;
    U  I332;
    U  I333;
    U  I334;
    UP  * I335;
    U  * I336;
    U  * I337;
    U  I338 :15;
    U  I339 :14;
    U  I340 :1;
    U  I341 :1;
    U  I342 :1;
    U  I343 :3;
    U  I344 :1;
    U  I345 :1;
    U  I346 :17;
    U  I347 :3;
    U  I348 :5;
    U  I349 :2;
    U  I350 :1;
    U  I351 :31;
    struct scope * I352;
    U  I354;
    U  I355;
    U  I356;
    U  * I357;
    U  * I358;
    U  * I359;
    U  I360;
    U  I361;
    U  I362;
    struct pcbt * I363;
    U  I373;
    U  I374;
    U  I375;
    U  I376;
    void * I377;
    void * I378;
    void * I379;
    int I380;
    U  * I381;
    U  I382;
    U  I383;
    U  I384;
    U  I385;
    U  I386;
    U  I387;
    U  I388;
    void * I389;
    UP  * I390;
    U  I391;
    U  I392;
    void * I393;
    U  I394;
    void * I395;
    U  I396;
    void * I397;
    U  I398;
    int (* I399)(void);
    int (* I400)(void);
    void * I401;
    void * I402;
    void * I403;
    U  I404;
    U  I405;
    U  I406;
    U  I407;
    U  I408;
    U  I409;
    char * I410;
    U  I411;
    U  * I412;
    U  I413;
    U  * I414;
    U  I415;
    U  I416;
    U  I417;
    U  I418;
    U  I419;
    U  I420;
    U  * I421;
    U  I422;
    U  I423;
    U  * I424;
    U  I425;
    U  I426;
    U  * I427;
    char * I428;
    U  I429;
    U  I430;
    U  I431;
    U  I432;
    U  * I433;
    U  * I434;
    U  I435;
    U  * I436;
    U  * I437;
    U  I438;
    U  I439;
    U  I440;
    U  I441;
    struct cosim_info * I442;
    U  I444;
    U  * I445;
    U  I446;
    U  I447;
    U  * I448;
    U  I449;
    U  * I450;
    U  I451;
    U  I452;
    U  * I453;
    U  I454;
    U  * I455;
    U  I456;
    U  * I457;
    U  I458;
    U  I459;
    U  I460;
    U  I461;
    U  I462;
    U  I463;
    U  I464;
    U  I465;
    U  I466;
    U  * I467;
    U  * I468;
    void (* I469)(void);
    U  * I470;
    UP  * I471;
    struct mhdl_outInfo * I472;
    UP  * I474;
    U  I475;
    UP  * I476;
    U  I477;
    void * I478;
    U  * I479;
    void * I480;
    char * I481;
    int (* I482)(void);
    U  * I483;
    char * I484;
    char * I485;
    U  I486;
    U  * I487;
    char * I488;
    U  I489;
    struct regInitInfo * I490;
    UP  * I492;
    U  * I493;
    char * I494;
    U  I495;
    U  I496;
    U  I497;
    U  I498;
    U  I499;
    U  I500;
    U  I501;
    U  I502;
    U  * I503;
    U  * I504;
    U  I505;
    U  I506;
    U  I507;
    U  I508;
    UP  * I509;
    U  I510;
    UP  * I511;
    U  I512;
    U  I513;
    U  I514;
    U  * I515;
    U  I516;
    U  I517;
    U  I518;
    U  * I519;
    U  * I520;
    UP  * I521;
    UP  * I522;
    void * I523;
    UP  I524;
    void * I525;
    void * I526;
    void * I527;
    void * I528;
    void * I529;
    UP  I530;
    U  * I531;
    U  * I532;
    void * I533;
    U  I534 :1;
    U  I535 :31;
    U  I536;
    U  I537;
    U  I538;
    int I539;
    void * I540;
    UP  * I541;
    U  * I542;
    U  I543;
    char * I544;
    U  * I545;
    U  * I546;
    char * I547;
    int * I548;
    UP  * I549;
    struct etype * I550;
    U  I597;
    U  I598;
    U  I599;
    U  * I600;
    void * I601;
    U  I602;
    U  I603;
    void * I604;
    U  I605;
    U  I606;
    U  * I607;
    U  I608;
    U  * I609;
    U  I610;
    U  I611;
    U  * I612;
};
typedef struct pcbt {
    U  * I365;
    UP  I366;
    U  I367;
    U  I368;
    U  I369;
    U  I370;
    U  I371;
    U  I372;
} PCBT;
struct iptmpl {
    QIRD  * I683;
    struct vcs_globals_t * I684;
    void * I686;
    UP  I687;
    UP  I688;
    struct iptmpl * I679[2];
};
typedef unsigned long long FileOffset;
typedef struct _hsimPeriodL {
    char  I851[256];
    struct _hsimPeriodL * I814;
} HsimPeriodL;
typedef struct {
    U   I853[2];
    U  I854 :1;
    U  I855 :1;
    U  I856 :8;
    U  I857 :8;
    U  I858 :8;
    U  I859 :4;
    unsigned long long I860;
    unsigned long long I861;
    unsigned long long I862;
    unsigned long long I863;
    unsigned long long I864;
    U  I865;
    U  I866;
    U  I867;
    U  I868;
    HsimPeriodL  * I869;
    HsimPeriodL  * I870;
    U  I871;
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I872;
    InstNum  I873;
    U  I822;
    scalar  I874;
    UB  I875;
    UB  I876;
    UB  I877;
    U  I878;
    U  I879;
    U  I880;
    U  I881;
    U  I882;
    HsimSignalMonitor  * I883;
    RmaTimeStamp64  I884;
    U  I885;
    RmaTimeStamp64  I886;
} HsimNodeRecord;
typedef struct {
    RP  I887;
    RP  I679;
} RmaIbfIp;
typedef struct {
    RP  I887;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I676;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RmaEblk  I676;
    RP  I888;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I676;
    RP  I889;
    RP  I888;
    vec32  I890;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I676;
    RP  I889;
    RP  I888;
    vec32   I714[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I676;
    RP  I889;
    RP  I888;
    scalar   I891[1];
} RmaAnySchedECg;
typedef struct {
    RP  I892;
} RmaRootCbkCg;
typedef struct {
    RP  I893;
} RmaRootVcdCg;
typedef struct {
    RP  I894;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I676;
    RP  I895;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I672 :30;
    U  I896 :1;
    U  I897 :1;
    vec32  I745;
    U  I898;
    RP  I899;
    RP  I900;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I906;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I617;
    RmaIbfPcode   I906[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I906;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I907;
    U  I908 :3;
    U  I909 :1;
    U  I910 :1;
} RmaNbaGateOfn;
typedef struct {
    NBS  I911;
    RmaIbfPcode  I907;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct {
    U  I5;
    U  iinput;
    RP  I914;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    RP  I914;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I915;
    U  * I916;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I917;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I917;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I676;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I676;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I676;
    RP  pcode;
    RP  pfn;
    scalar  I918;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I919;
    RP  I920;
    RP  I921;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I676;
    RP  pcode;
    U  I822;
    U   I665[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I744;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I744;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1049;
        RP  I1297;
        RP  I1307;
    } I719;
    RmaIbfPcode  I907;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I922;
    RmaIbfPcode  I907;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I907;
    RmaMps  I923;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I924;
    RmaIbfPcode  I907;
    RmaEblk  I704;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I907;
    RmaMpspNewCsdf  I925;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I925;
    RmaIbfPcode  I907;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I634;
    RmaTransEventHdr  I828;
    RP  I741;
    RmaIbfPcode  I907;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I634;
    RmaTransEventHdr  I828;
    RP  I741;
    RmaIbfPcode  I907;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I634;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I926;
    U  I927;
    RmaTransEventHdr  I828;
    RP  I741;
    RmaIbfPcode  I907;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I926;
    U  I927;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I928;
    RmaTransEventHdr  I828;
    RP  I741;
    RmaIbfPcode  I907;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I928;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I744;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1297;
        RP  I1307;
    } I719;
    RmaIbfPcode  I907;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I744;
    RmaEblk  I676;
    RmaIbfPcode  I907;
} RmaPortDelay;
typedef struct TableAssign_ {
    struct TableAssign_ * I814;
    struct TableAssign_ * I735;
    U  I5;
    U  iinput;
    RP  ptable;
    RP  I917;
} TableAssign;
typedef struct {
    U  I5;
    RP  I735;
    RP  I930;
} RmaTableAssignList;
typedef struct {
    RP  I931;
} RmaWakeupListCg;
typedef struct {
    U  I932;
    U  I933;
    RmaTimeStamp   I934[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I935;
} RmaConditionsMdb;
typedef struct {
    RP  I814;
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I814;
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I947;
} RmaTcCoreConditional;
typedef struct {
    RP  I814;
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I947;
    RP  I948;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I814;
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I948;
    RP  I949;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I952;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I947;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I947;
    RP  I948;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I948;
    RP  I949;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I948;
    RP  I949;
    RP  I952;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    RP  I947;
    RP  I952;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I936;
    RP  I671;
    U  I937;
    scalar  I938;
    scalar  I939;
    US  I940 :1;
    US  I941 :1;
    US  I942 :1;
    US  I943 :1;
    US  I944 :1;
    US  I945 :1;
    US  I946 :5;
    U  I953;
    RP  I954;
    RP  I955;
    RP  I947;
    RP  I956;
    RP  I957;
    RmaTimeStamp  I958;
} RmaTcCoreNochange;
typedef struct {
    RP  I959;
    RP  I814;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I935;
    RmaTimeStamp  I960;
    scalar  I961;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I814;
    RP  I935;
    RmaTimeStamp  I960;
    scalar  I961;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I960;
    scalar  I961;
    US  I938;
    RP  I948;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I814;
    RmaTimeStamp  I960;
    scalar  I961;
    US  I938;
    RP  I948;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I948;
    RP  I962;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I952;
    RP  I948;
    RP  I962;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I814;
    RP  I948;
    RP  I962;
    U  I950;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I963;
    U  I964;
    FlatNodeNum  I965;
    U  I822;
    U  I966;
    U  I967;
    RmaIbfPcode  I907;
    union {
        scalar  I968;
        vec32  I969;
        scalar  * I970;
        vec32  * I971;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I814;
    RP  I735;
    RP  I972;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I973;
    U  I974 :1;
    U  I975 :1;
    U  I976 :1;
    U  I977 :4;
    U  I578 :25;
    U  I978;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1336;
        RmaSwitchGateInCbkListInfo  I2;
    } I648;
    RmaIbfPcode  I907;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I979;
    scalar  val;
    scalar  I176 :4;
    scalar  I980 :1;
    scalar  I981 :1;
    scalar  I982 :1;
    scalar  I983 :1;
    RP  I748;
    RP  I984;
    RP  I965;
    RP  I985;
    RP  I986;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I987;
    UB  I988;
    RmaNonEdgeLoadData1  * I989;
    RmaNonEdgeLoadData1  * I735;
} RmaNonEdgeLoadHdr1;
typedef struct RmaChildClockProp_ {
    RP  I748;
    RP  I990;
    RP  I965;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I989;
    RmaChildClockProp  * I735;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I991;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I176 :5;
    U  I177 :12;
    U  I178 :1;
    U  I179 :2;
    U  I180 :1;
    U  I181 :1;
    U  I182 :1;
    U  I183 :9;
    U  I184;
    U  I185;
    void (* pfn)(void * I187, char val);
};
typedef struct clock_data {
    U  I192 :1;
    U  I193 :1;
    U  I194 :1;
    U  I195 :1;
    U  I176 :5;
    U  I177 :12;
    U  I196 :6;
    U  I197 :1;
    U  I179 :2;
    U  I180 :1;
    U  I183 :1;
    U  I198;
    U  I199;
    U  I200;
    U  I184;
    U  I201;
    U  I202;
    U  I203;
    U  I204;
    U  I205;
} HdbsClockData;
struct clock_hiconn {
    U  I209;
    U  I210;
    U  I184;
    U  I179;
};
typedef struct _RmaDaiCg {
    RP  I992;
    RP  I993;
    U  I994;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I992;
    RP  I995;
    RP  I996;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I997;
} RmaDaiOptCg;
struct futq {
    struct futq * I689;
    struct futq * I691;
    RmaEblk  * I692;
    RmaEblk  * I693;
    U  I681;
};
struct sched_table {
    struct futq * I694;
    struct futq I695;
    struct hash_bucket * I696;
};
struct dummyq_struct {
    clock_struct  I1001;
    EBLK  * I1002;
    EBLK  * I1003;
    struct futq * I1004;
    struct futq * I1005;
    struct sched_table * I1006;
    struct millenium * I1008;
    EBLK  * I1010;
    EBLK  * I1011;
    EBLK  * I1012;
    EBLK  * I1013;
    EBLK  * I1014;
    EBLK  * I1015;
    EBLK  * I1016;
    EBLK  * I1017;
    EBLK  * I1018;
    EBLK  * I1019;
    EBLK  * I1020;
    EBLK  * I1021;
    EBLK  * I1022;
    EBLK  * I1023;
    EBLK  * I1024;
    EBLK  * I1025;
    EBLK  * I1026;
    EBLK  * I1027;
    MPS  * I1028;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I677;
    EBLK  * I1029;
    int I1030;
    struct _lqueue * I708;
} Queue;
typedef struct {
    EBLK  I1032;
    U  I1033;
    union {
        void * pHeap;
        Queue  * pList;
    } I648;
    Queue   I1034[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern FP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern UB  dummyScalar;
extern UB  fScalarIsForced;
extern UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern Qhdr  * lvlQueue;
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern UB  fNettypeIsForced;
extern UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(UB *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hsM_0_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_0_1__simv_daidir (UB  * pcode, scalar  val, U  I626, scalar  * I1053);
void  hsM_0_2__simv_daidir (UB  * pcode);
void  hsM_1_0__simv_daidir (UB  * pcode, scalar  val);
void  hsM_1_1__simv_daidir (UB  * pcode, scalar  val, U  I626, scalar  * I1053);
void  hsM_1_2__simv_daidir (UB  * pcode);
void  hsG_0 (struct dummyq_struct * I1041, EBLK  * I1042, U  I634);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

